### ISSUE TITLE
Check question count

### ISSUE THREAD

**Issue by cmaexamacademy** [nickdavis/cmaexamacademy.com#18]
@nickdavis Could you check the question count by section/topic? My staff has been adding questions but the totals by Section are off compared to their spreadsheet. Before I ask them to reconcile, which can be time consuming, I'd like to verify that the count is correct on your end. Here's the spreadsheet they are using to track: https://docs.google.com/spreadsheets/d/1k2jj5ZBmeG1nyxRjwC1rz_wqjWF4CPk5NxtR2V9uiEw/edit?usp=sharing

**Comment by nickdavis** [comment]
@cmaexamacademy 

## Adding filters for Question Type and Topic

I took a little time to add filters for both `Topic` and `Question Type` in the **TB. Questions** section of the WordPress admin to make it easier to check.

Here's what the filters looks like before any selections have been made (please note the count on the right).

<img width="915" alt="Screenshot 2019-10-07 at 10 39 05" src="https://user-images.githubusercontent.com/1030574/66301324-cf57a980-e8ee-11e9-8ac3-78d4c7ffadb1.png">

And here's what they look like with Multiple Choice (`Question Type`) and External Financial Reporting Decisions (`Topic`) selected. Again, please see the count on the right.

<img width="926" alt="Screenshot 2019-10-07 at 10 41 43" src="https://user-images.githubusercontent.com/1030574/66301566-42612000-e8ef-11e9-90b8-a46edbe3b33c.png">

Which matches the count on the front end (171).

<img width="396" alt="Screenshot 2019-10-07 at 10 43 56" src="https://user-images.githubusercontent.com/1030574/66301639-6ae91a00-e8ef-11e9-9696-7467c3a3b2dd.png">

However the spreadsheet suggests there should be 163.

## Why the difference?

Likely because, the front end table is showing a student's results (and total question count) across all multiple choice questions for a particular topic, **including both standalone multiple choice questions and multiple choice questions that are part of an Essay exercise**.

I'm assuming, however, the spreadsheet is showing a count for stand alone multiple choice questions only.

## Adding third filter (Exercise Type)

To make it easier to check then, I added a third filter `Exercise Type`, which allows you to identify the standalone multiple choice questions only.

<img width="760" alt="Screenshot 2019-10-07 at 10 59 25" src="https://user-images.githubusercontent.com/1030574/66302940-ce744700-e8f1-11e9-85bf-6c67c7043e11.png">

This then gives us a total count of 162 standalone multiple choice questions added to WordPress for the External Financial Reporting Decisions section. Which is, of course, 1 less than the spreadsheet (so this would need checking by your team).

## Current section count comparison (actual vs expected)

Hopefully with these filters your team can quickly narrow down and identify any sections where the count is not as expected and amend the questions appropriately.

However, to save time, I've listed the differences in WordPress vs `MCQs Actual column` on the spreadsheet by Part / Section below, at the time of writing.

- **P1SA (-1, vs expected)**
- **P2SB (+1)**
- P1SC (0, as expected)
- **P1SD (-1)**
- P1SE (0)
- P1SF (n/a)

- P2SA (0)
- P2SB (0)
- P2SC (0)
- P2SD (0)
- P2SE (0)
- P2SF (n/a)

If you want any other filters or have any other questions, please feel free to re-open.

**Comment by cmaexamacademy** [comment]
@nickdavis these filters are going to be a huge help when we reconcile the db to our spreadsheet. And yes you are are correct in thinking that the spreadsheet is only for MCQs.
